name = "Dom moD pack"
author = "Rornor"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c73ace0720bb7bb2e0d96da91964e0665dcbcbca80fe0fa829f0897c27e03ea3"

[versions]
forge = "47.4.22"
minecraft = "1.20.1"
