name = "Dom moD pack"
author = "Rornor"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eb4333ab252a291589bda7e242b698223ee0a04e2d00e7162ea4cc47a9d3b164"

[versions]
forge = "47.4.22"
minecraft = "1.20.1"
