name = "Dom moD pack"
author = "Rornor"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f8623c359ffc9881f05bd4dd9e938647238e76e4e431acab87b8a838396d574a"

[versions]
forge = "47.4.22"
minecraft = "1.20.1"
